// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbWDjVg4tex61XJggID9fSuBcJyShSjH0',
    appId: '1:520458945876:web:499ddbe05886bac55b74c1',
    messagingSenderId: '520458945876',
    projectId: 'booking-mobile-6fa99',
    authDomain: 'booking-mobile-6fa99.firebaseapp.com',
    storageBucket: 'booking-mobile-6fa99.firebasestorage.app',
    measurementId: 'G-93QJ25063F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA9WGpTrYLTiFYh5YWr5g5S4j466LS-kI',
    appId: '1:520458945876:android:3a0d5bacf051e94b5b74c1',
    messagingSenderId: '520458945876',
    projectId: 'booking-mobile-6fa99',
    storageBucket: 'booking-mobile-6fa99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5AB94c2Nyn-UTQYY6tyr7DAF0HGfIt8c',
    appId: '1:520458945876:ios:ed280a9714dc53495b74c1',
    messagingSenderId: '520458945876',
    projectId: 'booking-mobile-6fa99',
    storageBucket: 'booking-mobile-6fa99.firebasestorage.app',
    iosClientId: '520458945876-v11l6dpj7cl4f4j6c9vcskl0hdf8tq9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.booking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5AB94c2Nyn-UTQYY6tyr7DAF0HGfIt8c',
    appId: '1:520458945876:ios:ed280a9714dc53495b74c1',
    messagingSenderId: '520458945876',
    projectId: 'booking-mobile-6fa99',
    storageBucket: 'booking-mobile-6fa99.firebasestorage.app',
    iosClientId: '520458945876-v11l6dpj7cl4f4j6c9vcskl0hdf8tq9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.booking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbWDjVg4tex61XJggID9fSuBcJyShSjH0',
    appId: '1:520458945876:web:b546606343e355095b74c1',
    messagingSenderId: '520458945876',
    projectId: 'booking-mobile-6fa99',
    authDomain: 'booking-mobile-6fa99.firebaseapp.com',
    storageBucket: 'booking-mobile-6fa99.firebasestorage.app',
    measurementId: 'G-0JMZ2K3E2M',
  );
}
